---
- name: SA Telemetry Post Install for Masters
  hosts: masters
  tasks:
    - import_role:
        name: sa_telemetry_postinstall
        tasks_from: masters.yml
      vars:
        sa_telemetry_postinstall_namespace: "{{ sa_telemetry_namespace }}"

- name: SA Telemetry Post Install for Nodes
  hosts: nodes
  tasks:
    - import_role:
        name: sa_telemetry_postinstall
        tasks_from: nodes.yml
