---
- name: oVirt infra
  hosts: engine
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` variable using ansible-vault
    - ../vars/{{ password_file }}

  tasks:
    - include_role:
        name: oVirt.vm-infra
      tags:
        - install-vm-infra

    - set_fact:
        ansible_service_broker_registry_auth_type: ""
        ansible_service_broker_registry_auth_name: ""

    - fail:
        msg: Bail out because we are deleting the virtual machines. Expected error.
      when: vm_state == "absent"

# WARNING: this will fail with Ansible 2.7.0 (use 2.6.x or >= 2.7.1)
- name: Run prerequisites for OpenShift
  import_playbook: openshift-ansible-playbooks/prerequisites.yml

- name: Install OpenShift on the nodes
  import_playbook: openshift-ansible-playbooks/deploy_cluster.yml

- name: SA telemetry post-install
  import_playbook: sa-telemetry-postinstall.yml
