apiVersion: v1
kind: Pod
metadata:
  name: openshift-installer
spec:
  containers:
  - args:
    - ${OPENSHIFT_INSTALLER_ARGS}
    env: null
    image: ${OPENSHIFT_INSTALLER_IMAGE_STREAM_TAG}
    imagePullPolicy: IfNotPresent
    name: openshift-installer
    volumeMounts:
    - mountPath: ${VOLUME_MOUNT_PATH}
      name: ${VOLUME_NAME}
      readOnly: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: default
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-installer
      from:
        kind: ImageStreamTag
        name: ${OPENSHIFT_INSTALLER_IMAGE_STREAM_TAG}
        namespace: ${NAMESPACE}
      lastTriggeredImage: ""
    type: ImageChange
  - type: ConfigChange
  volumes:
  - name: ${VOLUME_NAME}
    persistentVolumeClaim:
      claimName: ${CLAIM_NAME}
