---
- name: Replace secrets in install-config.yml
  hosts: localhost

  vars:
    ssh_public_key: " {{ lookup('env', 'SSH_PUBLIC_KEY') | string }}"
    workspace: "{{ lookup('env','WORKSPACE') }}"
    tectonic_secret: " {{ lookup('env','TECTONIC_SECRET') | string}}" # add whitespace to prevent ansible interpreting it :(

  tasks:
  - name: Debug secret
    debug:
        msg: "{{ tectonic_secret }}"

  - name: Replace Cluster Secret
    replace:
      path: '{{ workspace }}/ignition_config/install-config.yml'
      regexp: '#SSH_KEYS#'
      replace: '{{ ssh_public_key }}'

  - name: Replace Tectonic Secret
    replace:
      path: '{{ workspace }}/ignition_config/install-config.yml'
      regexp: '#PULL_SECRET#'
      replace: '{{ tectonic_secret }}'
