---
- src: oVirt.engine-setup
  version: 1.1.5
- src: oVirt.infra
  version: 1.1.9
- src: oVirt.image-template
  version: 1.1.8
- src: oVirt.repositories
  version: 1.1.2
- src: oVirt.vm-infra
  version: 1.1.11
- src: https://github.com/openshift/openshift-ansible
  name: openshift.openshift-ansible
  version: "openshift-ansible-3.11.44-1"
